### ISSUE TITLE
Ihre Bewerbung bei Douglas

### ISSUE THREAD

**Issue by frankvontempelhoff** [tmzint/sbt-vulcanize#1]
Hallo Herr Zint,

leider hatte HR ihnen ohne Rücksprache mit mir voreilig eine Absage erteilt, ohne dass ich Zeit fand Ihr CV zu sichten. 
Es würde mich daher sehr freuen, wenn Sie mir die Gelegenheit geben könnten, mir Ihr CV per Email an f.vontempelhoff@douglas.de zuzusenden, damit ich mir ein Bild von Ihnen machen kann.

Vielen Dank!

Frank von Tempelhoff
Leiter Softwaredevelopment

**Comment by tmzint** [comment]
closed for being off-topic.
